SELECT
MARC_1.MATNR as MATERIAL,
MARC_1.MAKTX as DESCRIPTION,
MARC_1.STAWN_US as HS_US,
MARC_2.STAWN_EU as HS_EU,
MARC_1.HERKL as COO

FROM
(((_SYS_BIC.MARA LEFT JOIN
      (SELECT
      MAKT.MATNR,
      MAKT.MAKTX,
      MARC.STAWN as STAWN_US,
      MARC.HERKL
      FROM
      _SYS_BIC.MAKT INNER JOIN _SYS_BIC.MARC on MAKT.MATNR = MARC.MATNR
      WHERE
      MARC.WERKS = '2000') MARC_1 on MARA.MATNR = MARC_1.MATNR)
  LEFT JOIN
      (SELECT
        MAKT.MATNR,
        MAKT.MAKTX,
        MARC.STAWN as STAWN_EU,
        MARC.HERKL
        FROM
        _SYS_BIC.MAKT INNER JOIN _SYS_BIC.MARC on MAKT.MATNR = MARC.MATNR
        WHERE
        MARC.WERKS = '3000'
          OR
        MARC.WERKS = '3120') MARC_2 on MARC_1.MATNR = MARC_2.MATNR)
  INNER JOIN _SYS_BIC.NS_LIPS on MARC_1.MATNR = NS_LIPS.MATNR)
  INNER JOIN _SYS_BIC.NS_LIKP on NS_LIPS.VBELN = NS_LIKP.VBELN

WHERE
  NS_LIKP.WADAT_IST > add_years(current_date,-3)

UNION
SELECT
MARC_1.MATNR as MATERIAL,
MARC_1.MAKTX as DESCRIPTION,
MARC_1.STAWN_US as HS_US,
MARC_2.STAWN_EU as HS_EU,
MARC_1.HERKL as COO

FROM
((_SYS_BIC.MARA LEFT JOIN
      (SELECT
      MAKT.MATNR,
      MAKT.MAKTX,
      MARC.STAWN as STAWN_US,
      MARC.HERKL
      FROM
      _SYS_BIC.MAKT INNER JOIN _SYS_BIC.MARC on MAKT.MATNR = MARC.MATNR
      WHERE
      MARC.WERKS = '2000') MARC_1 on MARA.MATNR = MARC_1.MATNR)
  LEFT JOIN
      (SELECT
        MAKT.MATNR,
        MAKT.MAKTX,
        MARC.STAWN as STAWN_EU,
        MARC.HERKL
        FROM
        _SYS_BIC.MAKT INNER JOIN _SYS_BIC.MARC on MAKT.MATNR = MARC.MATNR
        WHERE
        MARC.WERKS = '3000'
          OR
        MARC.WERKS = '3120') MARC_2 on MARC_1.MATNR = MARC_2.MATNR)
    INNER JOIN _SYS_BIC.NS_EKPO on MARC_1.MATNR = NS_EKPO.MATNR
WHERE
  (NS_EKPO.AEDAT > add_years(current_date,-1)
  AND NS_EKPO.EBELN LIKE '45%')
ORDER BY MATERIAL
