SELECT
count(MERGED_DATASET.LineID) as CountOfLineID,
MERGED_DATASET.Date,
MERGED_DATASET.AUART,
MERGED_DATASET.DEPCT,
MERGED_DATASET.DESCT,
MERGED_DATASET.LICTY,
round(sum(MERGED_DATASET.VALUE),2) as SumOfValue,
MERGED_DATASET.ECCN,
MERGED_DATASET.OVERRIDE,
MERGED_DATASET.EXTNO,
MERGED_DATASET.NAME1

FROM(
    SELECT
    GTS_sub.LineID,
    GTS_sub.Date,
    NS_VBAK.AUART,
    GTS_sub.DEPCT,
    GTS_sub.DESCT,
    GTS_sub.LICTY,
    GTS_sub.VALUE,
    GTS_sub.ECCN,
    GTS_sub.OVERRIDE,
    GTS_sub.EXTNO,
    KNA1.NAME1

    FROM ((_SYS_BIC.NS_LIPS INNER JOIN ((
        (SELECT
        CONCAT(CV_CORREF.REFNO,CV_CUIT.ITVSY) AS LineID,
        CV_CUIT.CTYPL as DEPCT,
        CV_LEGCON.LNDAB as DESCT,
        CV_LEGCON.LICTY,
        Left(CV_CORREF.REFDT,6) AS Date,
        CV_PNTPR.PRVSY as MATERIAL,
        Right(CV_CORREF.REFNO,10) AS REFNO1,
        CV_CUIT.ITVSY as LINE,
        CV_CUIT.NETVAL_FLT as VALUE,
        CV_CTSNUM.CCNGN as ECCN,
        CV_LEGCON.CRECO as OVERRIDE,
        CV_LCLIC.EXTNO

        FROM _SYS_BIC."prd.global.gts/CV_LCLIC" CV_LCLIC INNER JOIN ((_SYS_BIC."prd.global.gts/CV_PNTPR" CV_PNTPR
          INNER JOIN ((_SYS_BIC."prd.global.gts/CV_CORREF" CV_CORREF
            INNER JOIN _SYS_BIC."prd.global.gts/CV_LEGCON" CV_LEGCON ON CV_CORREF.GUID_MOBJ = CV_LEGCON.GUID_MOBJ)
            INNER JOIN _SYS_BIC."prd.global.gts/CV_CUIT" CV_CUIT ON CV_LEGCON.GUID_POBJ = CV_CUIT.GUID_CUIT)
              ON CV_PNTPR.GUID_PR = CV_CUIT.GUID_PR)
            INNER JOIN (_SYS_BIC."prd.global.gts/CV_PRCTS" CV_PRCTS
              INNER JOIN _SYS_BIC."prd.global.gts/CV_CTSNUM" CV_CTSNUM ON CV_PRCTS.GUID_CTSNUM = CV_CTSNUM.GUID_CTSNUM)
                ON CV_CUIT.GUID_PR = CV_PRCTS.GUID_PR)
                ON CV_LCLIC.GUID_LCLIC = CV_LEGCON.GUID_LCLIC

        WHERE (CV_CORREF.REFDT>add_years(current_date,-3)
          AND CV_CORREF.OBJTP='LIKP')

        GROUP BY
        CV_CUIT.CTYPL,
        CV_LEGCON.LNDAB,
        CV_LEGCON.LICTY,
        Left(CV_CORREF.REFDT,6),
        CV_PNTPR.PRVSY,
        Right(CV_CORREF.REFNO,10),
        CV_CORREF.REFNO,
        CV_CUIT.NETVAL_FLT,
        CV_CUIT.ITVSY,
        CV_CTSNUM.CCNGN,
        CV_LEGCON.CRECO,
        CV_LCLIC.EXTNO
        )
    GTS_sub INNER JOIN _SYS_BIC.NS_LIKP ON GTS_sub.REFNO1 = NS_LIKP.VBELN) INNER JOIN _SYS_BIC.KNA1 ON NS_LIKP.KUNNR = KNA1.KUNNR) ON NS_LIPS.VBELN = NS_LIKP.VBELN)
    LEFT JOIN _SYS_BIC.NS_VBAP ON (NS_LIPS.VGPOS = NS_VBAP.POSNR) AND (NS_LIPS.VGBEL = NS_VBAP.VBELN))
    LEFT JOIN _SYS_BIC.NS_VBAK ON NS_VBAP.VBELN = NS_VBAK.VBELN

    GROUP BY
    GTS_sub.LineID,
    GTS_sub.VALUE,
    GTS_sub.Date,
    NS_VBAK.AUART,
    GTS_sub.DEPCT,
    GTS_sub.DESCT,
    GTS_sub.LICTY,
    GTS_sub.ECCN,
    GTS_sub.OVERRIDE,
    GTS_sub.EXTNO,
    KNA1.NAME1) MERGED_DATASET

    GROUP BY
    MERGED_DATASET.Date,
    MERGED_DATASET.AUART,
    MERGED_DATASET.DEPCT,
    MERGED_DATASET.DESCT,
    MERGED_DATASET.LICTY,
    MERGED_DATASET.ECCN,
    MERGED_DATASET.OVERRIDE,
    MERGED_DATASET.EXTNO,
    MERGED_DATASET.NAME1
    ;

